version: '3.7'
services:

  influxdb:
    image: "influxdb:1.8"
    hostname: "monitoring_influxdb"
    container_name: monitoring_influxdb
    ports: 
      - "8086:8086"
      - "8082:8082"
      # - "8089:8089/udp"
    volumes:
      - "/home/georgemanakanatas/Documents/projects/tick_stack/data/influxdb:/var/lib/influxdb"
      - "/home/georgemanakanatas/Documents/projects/tick_stack/config/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf"
    # environment: # in case there is a need to setup an account from scratch
    #   DOCKER_INFLUXDB_INIT_MODE: setup
    #   DOCKER_INFLUXDB_INIT_USERNAME: login
    #   DOCKER_INFLUXDB_INIT_PASSWORD: password
    #   DOCKER_INFLUXDB_INIT_ORG: org
    #   DOCKER_INFLUXDB_INIT_BUCKET: bucker
    #   DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: amdintoken
    networks:
      - monitornet

  chronograf:
    image: "chronograf:latest"
    hostname: "monitoring_chronograf"
    container_name: monitoring_chronograf
    ports: 
      - "8888:8888"
      # - "8089:8089/udp"
    volumes:
      - "/home/georgemanakanatas/Documents/projects/tick_stack/data/chronograf:/var/lib/chronograf"
    environment:
      INFLUXDB_URL: http://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092
    depends_on:
      - influxdb
    networks:
      - monitornet

  telegraf:
    image: "telegraf:latest"
    hostname: "monitoring_telegraf"
    container_name: monitoring_telegraf
    # ports:
    #   - 
    volumes:
      - "/home/georgemanakanatas/Documents/projects/tick_stack/config/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf"
    networks:
      - monitornet

  kapacitor:
    image: "kapacitor:latest"
    hostname: "monitoring_kapacitor"
    container_name: "monitoring_kapacitor"
    volumes:
      - "/home/georgemanakanatas/Documents/projects/tick_stack/kapacitor:/var/lib/kapacitor"
      - "/home/georgemanakanatas/Documents/projects/tick_stack/config/kapacitor/kapacitor.conf:/etc/kapacitor/kapacitor.conf"
    environment: 
      - "KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086"
    ports:
      - "9092:9092"
    networks:
      - monitornet
  
  grafana:
    container_name: grafana 
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    env_file:
      - 'env.grafana'
    volumes:
      # - ./grafana/etc/ssl/:/etc/ssl
      - ./grafana/etc/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/data/:/var/lib/grafana
      # - ./grafana/dashboards:/var/lib/grafana/dashboards
    links:
      - influxdb
    networks:
      - monitornet

networks:
    monitornet: